#!/bin/bash
emmanuel@emmanuel-ThinkPad-X1-Carbon-Gen-9:~/holbertonschool-shell/basics$ ls
0-current_working_directory  1-listit  README.md
emmanuel@emmanuel-ThinkPad-X1-Carbon-Gen-9:~/holbertonschool-shell/basics$ 

